FROM nginx:alpine

ENV ROOT_URL=
ENV API_ROOT=change-API_ROOT

ENV API_ROOT_LANDSCAPE=http://landscape:8081
ENV API_ROOT_USER=http://authentication:8082
ENV API_ROOT_DISCOVERY=http://discovery:8083

COPY docker/prod-env-updater.sh .
RUN chmod +x ./prod-env-updater.sh

COPY frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/

CMD ./prod-env-updater.sh && nginx -g "daemon off;"